algoritmo "semnome"
// Função :
// Autor :
// Data : 13/02/2023
// Seção de Declarações
var
a, b, c, soma: inteiro
inicio
escreva("Escreva o valor de a: ")
leia(a)
escreva("Escreva o valor de b: ")
leia(b)
escreva("Escreva o valor de c: ")
leia(c)

soma<-a+b
se (soma>c) entao
   escreval("A soma de A com B é maior que C")
senao
   escreval("A soma de A com B não é maior que C")
fimse
fimalgoritmo
